apiVersion: v1
kind: Service
metadata:
  name: rustify
spec:
  selector:
    app: rustify
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
