version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: rustify:dev
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/rustify
      - REDIS_URL=redis://cache:6379
      - BASE_URL=http://localhost:8080
      - RUST_LOG=info
    depends_on:
      - db
      - cache
    ports:
      - "8080:8080"
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rustify
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
volumes:
  pgdata:
