image:
  repository: ghcr.io/owner/rustify
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env: []
service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/affinity: ""
    nginx.ingress.kubernetes.io/enable-access-log: "true"
  hosts:
    - host: rustify.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

serviceMonitor:
  enabled: true
  interval: 15s
  scrapeTimeout: 5s
  labels: {}

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

pdb:
  enabled: true
  minAvailable: 1
