name: release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-push:
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
      - name: Auth to cluster via OIDC (stub)
        run: echo "Authenticate to your cluster using OIDC provider here"
      - name: Helm deploy
        uses: azure/setup-helm@v4
      - name: Deploy
        run: |
          helm upgrade --install rustify deploy/helm \
            --namespace rustify --create-namespace \
            --set image.repository=ghcr.io/${{ github.repository }} \
            --set image.tag=${{ github.ref_name }}
